.PHONY: all build-parse-sample tcp-sample clean

all: build-parse-sample tcp-sample

build-parse-sample:
	make -C BuildParseSample

tcp-sample:
	make -C TCPSample

clean:
	make -C BuildParseSample clean
	make -C TCPSample clean
